<Project>
	<PropertyGroup>
		<Version>12.0.3.4</Version>
		<Authors>沙漠尽头的狼</Authors>
		<RepositoryUrl>https://github.com/dotnet9/Zhijian</RepositoryUrl>
		<PackageProjectUrl>https://github.com/dotnet9/Zhijian</PackageProjectUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<RepositoryType>git</RepositoryType>
		<Copyright>https://codewf.com</Copyright>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
		<CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
</Project>
