<Project>
  <ItemGroup>
    <PackageVersion Include="AtomUI.Desktop.Controls" Version="6.0.0-build.2" />
    <PackageVersion Include="Avalonia" Version="12.0.3" />
    <PackageVersion Include="Avalonia.Desktop" Version="12.0.3" />
    <PackageVersion Include="Avalonia.Fonts.Inter" Version="12.0.3" />
    <PackageVersion Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.1" />
    <PackageVersion Include="CodeWF.Markdown.Lite.Themes" Version="12.0.3.1" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.1" />
    <PackageVersion Include="Lang.Avalonia.Json" Version="12.0.2.1" />
    <PackageVersion Include="VC-LTL" Version="5.3.1" />
    <PackageVersion Include="YY-Thunks" Version="1.2.2-Beta.2" />
  </ItemGroup>
</Project>
