<Project>
  <PropertyGroup>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <DebugType>portable</DebugType>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <IncludeSymbols>true</IncludeSymbols>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <UseArtifactsOutput>true</UseArtifactsOutput>
    <ArtifactsPath>$(MSBuildThisFileDirectory)artifacts\</ArtifactsPath>
    <PackageOutputPath>$(ArtifactsPath)packages\</PackageOutputPath>
    <Version>12.1.0.4</Version>
    <Authors>沙漠尽头的狼</Authors>
    <Company>沙漠尽头的狼</Company>
    <Product>Zhijian</Product>
    <RepositoryUrl>https://github.com/dotnet9/Zhijian</RepositoryUrl>
    <PackageProjectUrl>https://codewf.com</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <RepositoryType>git</RepositoryType>
    <Copyright>Copyright © 沙漠尽头的狼. https://codewf.com</Copyright>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
