//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zhijian;

public static class ZhijianL
{
    public static readonly string AppName = "Zhijian.ZhijianL.AppName";
    public static readonly string Untitled = "Zhijian.ZhijianL.Untitled";
    public static readonly string FileMenu = "Zhijian.ZhijianL.FileMenu";
    public static readonly string New = "Zhijian.ZhijianL.New";
    public static readonly string NewWindow = "Zhijian.ZhijianL.NewWindow";
    public static readonly string Open = "Zhijian.ZhijianL.Open";
    public static readonly string OpenFolder = "Zhijian.ZhijianL.OpenFolder";
    public static readonly string RecentFiles = "Zhijian.ZhijianL.RecentFiles";
    public static readonly string NoRecentFiles = "Zhijian.ZhijianL.NoRecentFiles";
    public static readonly string Save = "Zhijian.ZhijianL.Save";
    public static readonly string SaveAs = "Zhijian.ZhijianL.SaveAs";
    public static readonly string OpenFileLocation = "Zhijian.ZhijianL.OpenFileLocation";
    public static readonly string Close = "Zhijian.ZhijianL.Close";
    public static readonly string EditMenu = "Zhijian.ZhijianL.EditMenu";
    public static readonly string Undo = "Zhijian.ZhijianL.Undo";
    public static readonly string Redo = "Zhijian.ZhijianL.Redo";
    public static readonly string AddSibling = "Zhijian.ZhijianL.AddSibling";
    public static readonly string AddChild = "Zhijian.ZhijianL.AddChild";
    public static readonly string Promote = "Zhijian.ZhijianL.Promote";
    public static readonly string Demote = "Zhijian.ZhijianL.Demote";
    public static readonly string MoveUp = "Zhijian.ZhijianL.MoveUp";
    public static readonly string MoveDown = "Zhijian.ZhijianL.MoveDown";
    public static readonly string AddNote = "Zhijian.ZhijianL.AddNote";
    public static readonly string EditNote = "Zhijian.ZhijianL.EditNote";
    public static readonly string DeleteNode = "Zhijian.ZhijianL.DeleteNode";
    public static readonly string CopyAsMarkdown = "Zhijian.ZhijianL.CopyAsMarkdown";
    public static readonly string ThemeMenu = "Zhijian.ZhijianL.ThemeMenu";
    public static readonly string DarkTheme = "Zhijian.ZhijianL.DarkTheme";
    public static readonly string LightTheme = "Zhijian.ZhijianL.LightTheme";
    public static readonly string LanguageMenu = "Zhijian.ZhijianL.LanguageMenu";
    public static readonly string SimplifiedChinese = "Zhijian.ZhijianL.SimplifiedChinese";
    public static readonly string TraditionalChinese = "Zhijian.ZhijianL.TraditionalChinese";
    public static readonly string English = "Zhijian.ZhijianL.English";
    public static readonly string Japanese = "Zhijian.ZhijianL.Japanese";
    public static readonly string HelpMenu = "Zhijian.ZhijianL.HelpMenu";
    public static readonly string Feedback = "Zhijian.ZhijianL.Feedback";
    public static readonly string SubmitFeature = "Zhijian.ZhijianL.SubmitFeature";
    public static readonly string SubmitPr = "Zhijian.ZhijianL.SubmitPr";
    public static readonly string Github = "Zhijian.ZhijianL.Github";
    public static readonly string AboutMenu = "Zhijian.ZhijianL.AboutMenu";
    public static readonly string OpenWebsite = "Zhijian.ZhijianL.OpenWebsite";
    public static readonly string Changelog = "Zhijian.ZhijianL.Changelog";
    public static readonly string Thanks = "Zhijian.ZhijianL.Thanks";
    public static readonly string About = "Zhijian.ZhijianL.About";
    public static readonly string FilesTab = "Zhijian.ZhijianL.FilesTab";
    public static readonly string OutlineTab = "Zhijian.ZhijianL.OutlineTab";
    public static readonly string MindMapTitle = "Zhijian.ZhijianL.MindMapTitle";
    public static readonly string MarkdownPlaceholder = "Zhijian.ZhijianL.MarkdownPlaceholder";
    public static readonly string ToggleToOutline = "Zhijian.ZhijianL.ToggleToOutline";
    public static readonly string ToggleToMarkdown = "Zhijian.ZhijianL.ToggleToMarkdown";
    public static readonly string CenterTopicPlaceholder = "Zhijian.ZhijianL.CenterTopicPlaceholder";
    public static readonly string TopicPlaceholder = "Zhijian.ZhijianL.TopicPlaceholder";
    public static readonly string NotePlaceholder = "Zhijian.ZhijianL.NotePlaceholder";
    public static readonly string MiniMap = "Zhijian.ZhijianL.MiniMap";
    public static readonly string CenterRoot = "Zhijian.ZhijianL.CenterRoot";
    public static readonly string ZoomOut = "Zhijian.ZhijianL.ZoomOut";
    public static readonly string ZoomIn = "Zhijian.ZhijianL.ZoomIn";
    public static readonly string ResetZoom = "Zhijian.ZhijianL.ResetZoom";
    public static readonly string Ready = "Zhijian.ZhijianL.Ready";
    public static readonly string EmptyMindMap = "Zhijian.ZhijianL.EmptyMindMap";
    public static readonly string FolderSummaryClosed = "Zhijian.ZhijianL.FolderSummaryClosed";
    public static readonly string FolderSummaryOpen = "Zhijian.ZhijianL.FolderSummaryOpen";
    public static readonly string NodeSummary = "Zhijian.ZhijianL.NodeSummary";
    public static readonly string NodeSummarySelected = "Zhijian.ZhijianL.NodeSummarySelected";
    public static readonly string HistorySummary = "Zhijian.ZhijianL.HistorySummary";
    public static readonly string StatusNewDocument = "Zhijian.ZhijianL.StatusNewDocument";
    public static readonly string StatusNewWindow = "Zhijian.ZhijianL.StatusNewWindow";
    public static readonly string StatusOpening = "Zhijian.ZhijianL.StatusOpening";
    public static readonly string StatusOpenFolder = "Zhijian.ZhijianL.StatusOpenFolder";
    public static readonly string StatusSaved = "Zhijian.ZhijianL.StatusSaved";
    public static readonly string StatusCopiedMarkdown = "Zhijian.ZhijianL.StatusCopiedMarkdown";
    public static readonly string StatusThemeChanged = "Zhijian.ZhijianL.StatusThemeChanged";
    public static readonly string StatusLanguageChanged = "Zhijian.ZhijianL.StatusLanguageChanged";
    public static readonly string TourWelcomeTitle = "Zhijian.ZhijianL.TourWelcomeTitle";
    public static readonly string TourWelcomeDescription = "Zhijian.ZhijianL.TourWelcomeDescription";
    public static readonly string TourOutlineTitle = "Zhijian.ZhijianL.TourOutlineTitle";
    public static readonly string TourOutlineDescription = "Zhijian.ZhijianL.TourOutlineDescription";
    public static readonly string TourToggleTitle = "Zhijian.ZhijianL.TourToggleTitle";
    public static readonly string TourToggleDescription = "Zhijian.ZhijianL.TourToggleDescription";
    public static readonly string TourMindMapTitle = "Zhijian.ZhijianL.TourMindMapTitle";
    public static readonly string TourMindMapDescription = "Zhijian.ZhijianL.TourMindMapDescription";
    public static readonly string TourStatusTitle = "Zhijian.ZhijianL.TourStatusTitle";
    public static readonly string TourStatusDescription = "Zhijian.ZhijianL.TourStatusDescription";
}
