










//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CodeWF.MindView.I18n
{

    public static class MindViewL
    {

        public static readonly string CenterTopicPlaceholder = "CodeWF.MindView.MindViewL.CenterTopicPlaceholder";

        public static readonly string TopicPlaceholder = "CodeWF.MindView.MindViewL.TopicPlaceholder";

        public static readonly string NotePlaceholder = "CodeWF.MindView.MindViewL.NotePlaceholder";

        public static readonly string AddSiblingText = "CodeWF.MindView.MindViewL.AddSiblingText";

        public static readonly string AddChildText = "CodeWF.MindView.MindViewL.AddChildText";

        public static readonly string PromoteText = "CodeWF.MindView.MindViewL.PromoteText";

        public static readonly string DemoteText = "CodeWF.MindView.MindViewL.DemoteText";

        public static readonly string MoveUpText = "CodeWF.MindView.MindViewL.MoveUpText";

        public static readonly string MoveDownText = "CodeWF.MindView.MindViewL.MoveDownText";

        public static readonly string AddNoteText = "CodeWF.MindView.MindViewL.AddNoteText";

        public static readonly string EditNoteText = "CodeWF.MindView.MindViewL.EditNoteText";

        public static readonly string DeleteNodeText = "CodeWF.MindView.MindViewL.DeleteNodeText";

        public static readonly string DragNodeTip = "CodeWF.MindView.MindViewL.DragNodeTip";

        public static readonly string UntitledTopic = "CodeWF.MindView.MindViewL.UntitledTopic";

        public static readonly string DefaultRootTitle = "CodeWF.MindView.MindViewL.DefaultRootTitle";

        public static readonly string JsonChildTitle = "CodeWF.MindView.MindViewL.JsonChildTitle";

        public static readonly string JsonItemTitle = "CodeWF.MindView.MindViewL.JsonItemTitle";

        public static readonly string CsvRecordTitle = "CodeWF.MindView.MindViewL.CsvRecordTitle";

        public static readonly string CsvColumnTitle = "CodeWF.MindView.MindViewL.CsvColumnTitle";

        public static readonly string ParseFailed = "CodeWF.MindView.MindViewL.ParseFailed";

        public static readonly string XMindContentMissing = "CodeWF.MindView.MindViewL.XMindContentMissing";

        public static readonly string XMindJsonMissingRootTopic = "CodeWF.MindView.MindViewL.XMindJsonMissingRootTopic";

        public static readonly string XMindXmlMissingRootTopic = "CodeWF.MindView.MindViewL.XMindXmlMissingRootTopic";

        public static readonly string MetadataFormatLabel = "CodeWF.MindView.MindViewL.MetadataFormatLabel";

        public static readonly string MetadataPathLabel = "CodeWF.MindView.MindViewL.MetadataPathLabel";

        public static readonly string BaiduMindMapFormat = "CodeWF.MindView.MindViewL.BaiduMindMapFormat";

        public static readonly string ImageFormat = "CodeWF.MindView.MindViewL.ImageFormat";

        public static readonly string DrawIoDiagramTitle = "CodeWF.MindView.MindViewL.DrawIoDiagramTitle";

    }


}


