<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <IsPackable>false</IsPackable>
    <TargetFrameworks>net11.0;net11.0-windows</TargetFrameworks>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>..\..\logo.ico</ApplicationIcon>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <AvaloniaResource Include="..\..\logo.ico" Link="Assets\logo.ico" />
    <AvaloniaResource Include="..\..\logo.png" Link="Assets\logo.png" />
    <AvaloniaResource Include="..\..\logo.svg" Link="Assets\logo.svg" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AtomUI.Desktop.Controls" />
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="CodeWF.EventBus" />
    <PackageReference Include="CodeWF.Log.Core" />
    <PackageReference Include="CodeWF.Markdown.Lite.Themes" />
    <PackageReference Include="CodeWF.Tools.Core" />
    <PackageReference Include="Lang.Avalonia.Json" />
    <PackageReference Include="ReactiveUI.Avalonia" />
    <PackageReference Include="VC-LTL" />
    <PackageReference Include="YY-Thunks" Condition="'$(TargetFramework)' == 'net11.0-windows'" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CodeWF.MindView\CodeWF.MindView.csproj" />
    <ProjectReference Include="..\CodeWF.MindView.Themes\CodeWF.MindView.Themes.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="..\..\UpdateLog.md" Link="UpdateLog.md" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="..\..\使用手册.md" Link="使用手册.md" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <None Update="App.config">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <Compile Update="I18n\Language.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Language.tt</DependentUpon>
    </Compile>
    <None Update="I18n\Language.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Language.cs</LastGenOutput>
    </None>
    <None Update="I18n\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>I18n\Zhijian\%(Filename)%(Extension)</TargetPath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>
  <Target Name="RemoveDebugSymbolsFromPublish" AfterTargets="Publish" Condition="'$(Configuration)' == 'Release'">
    <ItemGroup>
      <PublishDebugSymbol Include="$(PublishDir)**\*.pdb" />
    </ItemGroup>
    <Delete Files="@(PublishDebugSymbol)" TreatErrorsAsWarnings="true" />
  </Target>
</Project>
